module.exports.xBTCPlaceAddress = "0xf26da11A1F82cA18Eca0C949944D7FC3Ff9b8518"; //the address of the liquidity pool you wish to track (0xaFF587846a44aa086A6555Ff69055D3380fD379a -> 0xBTC / wETH UniswapV3)
module.exports.blockStep = 2; //blocks to process per cycle
module.exports.blockTimeMS = 13230; //average time before an ethereum block is mined
module.exports.alchemyKey = "polygonalchemykey"; //alchemy https://dashboard.alchemyapi.io/
module.exports.ensNameSolverKey = "ethmainnetalchemykey"; //alchemy https://dashboard.alchemyapi.io/

module.exports.eventsBackupFile = "eventsBackup.csv"; //file to backup events to
module.exports.latestBlockBackupFile = "blockBackup.txt"; //file to backup latest block processed
//contract abi for the liquidity pool (only need the swap event)
module.exports.xBTCPlaceABI = [{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256[]","name":"x","type":"uint256[]"},{"indexed":false,"internalType":"uint256[]","name":"y","type":"uint256[]"},{"indexed":false,"internalType":"uint256[]","name":"color","type":"uint256[]"}],"name":"PixelsPlaced","type":"event"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256[]","name":"x","type":"uint256[]"},{"internalType":"uint256[]","name":"y","type":"uint256[]"},{"internalType":"uint256[]","name":"color","type":"uint256[]"}],"name":"placePixels","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"withdraw","outputs":[],"stateMutability":"nonpayable","type":"function"}]